import zdt_motor
import time

motor = zdt_motor.ZdtMotor("COM16", 1, 0.1)
motor.encoder_check()
time.sleep(0.5)
motor.zero_set()
time.sleep(0.5)
motor.relieve_lock_protect()
time.sleep(0.5)
motor.read_enc()
time.sleep(0.5)
motor.read_ena()
time.sleep(0.5)
motor.read_auto_zero()
time.sleep(0.5)
motor.read_lock()
time.sleep(0.5)
motor.read_pul()
time.sleep(0.5)
motor.read_pos()
time.sleep(0.5)
motor.read_perr()
time.sleep(0.5)
motor.div_set(100)
time.sleep(0.5)
motor.id_set(9)
time.sleep(0.5)
motor.ena_set(1)
time.sleep(0.5)
motor.vel_set(100, 100)
time.sleep(0.5)
motor.pos_set(100, 100, 100)
time.sleep(0.5)
motor.param_state("clear")
time.sleep(0.5)

